### ISSUE TITLE
jquery error

### ISSUE THREAD

**Issue by domguard** [theatlantic/django-chosen#5]
When adding the widget, in a django 1.3.1 admin site I just have this error in Firebug :

$ is not a function

http://localhost:8000/static/js/chosen.jquery_ready.js?v=1

Line 2

**Comment by ortsed** [comment]
Django chosen is set up to work with the older versions of Django, and since the jquery reference style has changed with 1.3, it won't work:

https://docs.djangoproject.com/en/dev/ref/contrib/admin/#modeladmin-media-definitions

We would like to have a new branch to work with 1.3, but it will take some time since we aren't ready to switch to 1.3 just yet.  If you'd like to create that branch with the change, that would be great.  Should simply be changing the references from $ -> django.jQuery
